# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_law_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='petition_local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daca peti\u0163ia e de nivel local, scrie denumirea exact\u0103 a localit\u0103\u0163ii '),
        ),
        migrations.AlterField(
            model_name='petition',
            name='petition_region',
            field=models.CharField(blank=True, choices=[('0', 'Municipiul Chi\u015fin\u0103u'), ('1', 'Municipiul B\u0103l\u0163i'), ('2', 'Municipiul Comrat'), ('3', 'Municipiul Tiraspol'), ('4', 'Municipiul Tighina (Bender)'), ('5', 'Anenii Noi'), ('6', 'Basarabeasca'), ('7', 'Briceni'), ('8', 'Cahul'), ('9', 'C\u0103l\u0103ra\u015fi'), ('10', 'Cantemir'), ('11', 'C\u0103u\u015feni'), ('12', 'Cimi\u015flia'), ('13', 'Dondu\u015feni'), ('14', 'Drochia'), ('15', 'Dubasari'), ('16', 'Edine\u0163'), ('17', 'F\u0103le\u015fti'), ('18', 'Flore\u015fti'), ('19', 'Glodeni'), ('20', 'H\xeence\u015fti'), ('21', 'Ialoveni'), ('22', 'Leova'), ('23', 'Nisporeni'), ('24', 'Ocni\u0163a'), ('25', 'Orhei'), ('26', 'Rezina'), ('27', 'R\xee\u015fcani'), ('28', 'S\xeengerei'), ('29', '\u015eold\u0103ne\u015fti'), ('30', 'Soroca'), ('31', '\u015etefan Vod\u0103'), ('32', 'Str\u0103\u015feni'), ('33', 'Taraclia'), ('34', 'Telene\u015fti'), ('35', 'Ungheni')], max_length=100, null=True, verbose_name='Daca peti\u0163ia e de nivel regional sau local, alege raionul/municipiul '),
        ),
    ]
