# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20160725_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='petition_level',
            field=models.CharField(choices=[('0', 'Na\u021bional'), ('1', 'Regional/Municipal'), ('2', 'Local')], default='Na\u0163ional', max_length=100, verbose_name='Alege nivelul peti\u021biei'),
        ),
    ]
