# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20160816_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='law',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='petition',
            name='width_field',
        ),
    ]
