# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_auto_20160816_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='law',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='petition',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
