# -*- coding: utf-8 -*-
"""
Django settings for trydjango18 project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#root of project

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'csqwlmc8s55o($rt6ozh7u+ui9zb-et00w$d90j8$^!nvj41_r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['*']

# POSTMARK_API_KEY     = 'fb47a445-1733-4983-a0f5-b30ca16da9e1'
# POSTMARK_SENDER      = 'initiativa@webmail.co.za'
# POSTMARK_TEST_MODE   = False
# POSTMARK_TRACK_OPENS = True
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 2525
EMAIL_HOST_USER = "initiativa.ong@mail.ru"
EMAIL_HOST_PASSWORD = "madagascar42"
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'Initiativa <initiativa.ong@mail.ru>'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# PETITION_FROM = EMAIL_HOST_USER
''' 
If using gmail, you will need to
unlock Captcha to enable Django 
to  send for you:
https://accounts.google.com/displayunlockcaptcha
'''



# Application definition

INSTALLED_APPS = (
    #django app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',

    
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_modalview',
    
    'django_comments' ,
    'fluent_comments',
    #third party apps
    'djangosecure',
    'sslserver', 
    'crispy_forms',
    'registration',

    

    'dynamic_scraper',
    #my apps
    'newsletter',
    # 'petition',


)


AUTH_PROFILE_MODULE = 'registration.RegistrationProfile'


MIDDLEWARE_CLASSES = (
    'djangosecure.middleware.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)



# SECURE_SSL_REDIRECT = False
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000 
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True



ROOT_URLCONF = 'trydjango18.urls'



# TEMPLATE_CONTEXT_PROCESSORS = (

#     'petition.context_processors.petition_form',
# )
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trydjango18.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'd59r891j4nvs6a',                      # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'tdjzqthlwfkeur',
        'PASSWORD': 'gPeF5fvSxLst83c4xNoldLvut0',
        'HOST': 'ec2-54-75-237-218.eu-west-1.compute.amazonaws.com',                      # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '5432',                      # Set to empty string for default.
    }
}


import dj_database_url
DATABASES = {}
DATABASES['default'] = dj_database_url.config(default='postgres://tdjzqthlwfkeur:gPeF5fvSxLst83c4xNoldLvut0@ec2-54-75-237-218.eu-west-1.compute.amazonaws.com:5432/d59r891j4nvs6a')







# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


AWS_STORAGE_BUCKET_NAME = 'initiativamd'
AWS_ACCESS_KEY_ID = 'AKIAI7FOPHKISF5V4ZEQ'
AWS_SECRET_ACCESS_KEY = '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'

# Tell django-storages that when coming up with the URL for an item in S3 storage, keep
# it simple - just use this domain plus the path. (If this isn't set, things get complicated).
# This controls how the `static` template tag from `staticfiles` gets expanded, if you're using it.
# We also use it in the next setting.
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

# This is used by the `static` template tag from `static`, if you're using that. Or if anything else
# refers directly to STATIC_URL. So it's safest to always set it.




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_LOCATION = './static'
STATIC_URL = '/static/'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    #'/var/www/static/',
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'


#Crispy FORM TAGs SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'


#DJANGO REGISTRATION REDUX SETTINGS
ACCOUNT_ACTIVATION_DAYS = 1
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1
LOGIN_REDIRECT_URL = '/'






FLUENT_COMMENTS_EXCLUDE_FIELDS = ( 'url','email','name')
AKISMET_API_KEY = "872551d45f85"
AKISMET_BLOG_URL = "http://initiativa.org"        # Optional, to override auto detection
AKISMET_IS_TEST = False                        # Enable to make test runs
COMMENTS_APP = 'fluent_comments'
COMMENTS_ALLOW_PROFANITIES = False
PROFANITIES_LIST =("fuck")# COMMENTS_XTD_CONFIRM_EMAIL = True

# COMMENTS_MODEL= 'mycomments.models.MyComment'

# COMMENTS_XTD_FORM_CLASS ='mycomments.forms.MyCommentForm'

# COMMENTS_XTD_SEND_HTML_EMAIL = True




# CSRF_FAILURE_VIEW = 'newsletter.views.csrf_failure'
